name: DailyChallenge
version: 1.0.6
author: AlphaShadows77
main: fr.alphashadows77.dailychallenge.Main
depend: [Vault]
commands:
  dailychallenge:
    description: Commande principale du plugin Daily Challenge
    aliases: dc
  modifychallenge:
    description: Permet de gérer les challenges
    permission: dailychallenge.modifychallenge
    aliases: mc
    usage: "§cUsage: /mc additems|addstats §fou §c/mc list <frequence> §cou §c/mc info <frequence> <challenge> §fou §c/mc add <daily|weekly|monthly> <money> <xp> <nom> §fou §c/mc remove <frequence> <challenge>"
  allowdailychallenge:
    description: Permet d'activer ou de désactiver la commande /dailychallenge
    permission: dailychallenge.allowdailychallenge
  forcechallenge:
    description: Permet de changer un challenge périodique manuellement
    permission: dailychallenge.forcechallenge
    aliases: fc
    usage: "§cUsage: /fc <frequence> <nom du challenge>"